# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8c9c607fce36eaa628991e9e456a34192a99a324d4923f67030d3a8a97cfa64f29a57427162c7546d1d41b4b02ed306a32b86406c9f926561f54f6b831685d37

test:
  secret_key_base: 51c1a1f7bfdcd26715d30b1c024d39a163834d9baa2e34b346045bdb13893a0f99b6797240a01d0460c0ee7383cdd8c040dcad558798b9f2d39d418c5d3cbaa7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
